baseURL = "https://lgf.im/"
relativeURLs = true
defaultContentLanguage = "zh-cn"
theme = "LoveIt"
title = "zu1k"

enableRobotsTXT = false
enableGitInfo = true
enableEmoji = true
hasCJKLanguage = true
paginate = 14
googleAnalytics = "G-TC5F2FT2NP"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    url = "https://github.com/zu1k"
    title = "GitHub"
    weight = 6


[params]
  version = "0.2.X"
  defaultTheme = "auto"  # 网站默认主题 ("light", "dark", "auto")
  gitRepo = "https://github.com/zu1k/blog"
  fingerprint = "sha256"  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
  dateFormat = "2006-01-02"
  images = ["/images/logo.png"]
  description = "A boy dreaming of traveling around the world.<br>This blog is used to record my study, thinking and life."
  keywords = ["zu1k", "zuik", "lgf", "lgf.im"]
  [params.app]
    title = "zu1k"
    noFavicon = false
    svgFavicon = ""
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"
  [params.search]
    enable = true
    type = "algolia"  # 搜索引擎的类型 ("lunr" （索引文件）, "algolia" （在线的索引服务）)
    contentLength = 4000  # 文章内容最长索引长度
    placeholder = ""  # 搜索框的占位提示语
    maxResultLength = 10  # 最大结果数目
    snippetLength = 50  # 结果内容片段长度
    highlightTag = "em"  # 搜索结果中高亮部分的 HTML 标签
    absoluteURL = true  # 是否在搜索索引中使用基于 baseURL 的绝对路径
    [params.search.algolia]
      index = "lgf.im"
      appID = "YQWA6EI2VD"
      searchKey = "3fb91006ba1d0ebed6e8e7a04bd25f40"
  [params.home]
    rss = 20  # RSS 文章数目
    [params.home.profile]
      enable = true
      avatarURL = "/images/logo.jpg"
      title = "zu1k"   # 主页显示的网站标题 (支持 HTML 格式)
      subtitle = "A boy dreaming of traveling around the world.<br>This blog is used to record my study, thinking and life."  # 主页显示的网站副标题
      typeit = true  # 是否为副标题显示打字机动画
      social = true  # 是否显示社交账号
      disclaimer = ""  # 免责声明 (支持 HTML 格式)
    [params.home.posts]
      enable = false
      # 主页每页显示文章数量
      paginate = 6
  [params.social]
    GitHub = "zu1k"
    Twitter = "zu1k_lv"
    Tumblr = "t.lgf.im/?site="
    Telegram = "peekfun"
    Email = "i@lgf.im"
    RSS = true

  [params.header]
    desktopMode = "fixed"   # 桌面端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"  # 移动端导航栏模式 ("fixed", "normal", "auto")
    # 页面头部导航栏标题配置
    [params.header.title]
      logo = "/images/logo.jpg" # LOGO 的 URL
      name = "zu1k" # 标题名称
      pre = "" # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标  #"<i class='far fa-kiss-wink-heart fa-fw'></i>"  
      post = ""  # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      typeit = false  # 是否为标题显示打字机动画

  # 页面底部信息配置
  [params.footer]
    enable = true
    custom = ''  # 自定义内容 (支持 HTML 格式)
    hugo = false  # 是否显示 Hugo 和主题信息
    copyright = true  # 是否显示版权信息
    author = true  # 是否显示作者
    since = 2017 # 网站创立年份
    icp = "" # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    # 许可协议信息 (支持 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Section (所有文章) 页面配置
  [params.section]
    paginate = 20  # list 页面每页显示文章数量
    dateFormat = "01-02"  # 日期格式 (月和日)
    rss = 20  # RSS 文章数目

  # List (目录或标签) 页面配置
  [params.list]
    paginate = 20  # list 页面每页显示文章数量
    dateFormat = "01-02"  # 日期格式 (月和日)
    rss = 20  # RSS 文章数目

  [params.page]
    hiddenFromHomePage = false    # 是否在主页隐藏
    hiddenFromSearch = false  # 是否在搜索结果中隐藏
    twemoji = false  # 是否使用 twemoji
    lightgallery = false  # 是否使用 lightgallery
    ruby = false  # 是否使用 ruby 扩展语法
    fraction = false  # 是否使用 fraction 扩展语法
    fontawesome = false  # 是否使用 fontawesome 扩展语法
    linkToMarkdown = true  # 是否显示原始 Markdown 文档内容的链接
    rssFullText = true  # 是否在 RSS 中显示全文内容
    [params.page.toc]
      enable = true  # 是否使用目录
      keepStatic = false  # 是否保持使用文章前面的静态目录
      auto = true  # 是否使侧边目录自动折叠展开
    [params.page.code]
      copy = true  # 是否显示代码块的复制按钮
      maxShownLines = 20 # 默认展开显示的代码行数
    # KaTeX 数学公式配置 (KaTeX https://katex.org/)
    [params.page.math]
      enable = false
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      # 默认行内定界符是 $ ... $ 和 \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
    # Mapbox GL JS 配置 (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      # 是否添加 NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
      navigation = true
      # 是否添加 GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
      geolocate = true
      # 是否添加 ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
      scale = true
      # 是否添加 FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
      fullscreen = true
    # Social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Whatsapp = false
      Tumblr = true
      Evernote = true
    [params.page.comment]
      enable = true
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      [params.page.comment.utterances]
        enable = true
        repo = "zu1k/comment"
        issueTerm = "url"
        label = "blog"
        lightTheme = "github-light"
        darkTheme = "github-dark"
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # located in "assets/" 位于 "assets/"
        # Or 或者
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # located in "assets/" 位于 "assets/"
        # Or 或者
        # someJavascript = "https://cdn.example.com/some.js"
    [params.page.seo]
      images = ["/images/logo.jpg"]
      # 出版者信息
      [params.page.seo.publisher]
        name = "zu1k"
        logoUrl = "https://lgf.im/images/logo.jpg"

  [params.typeit]
    speed = 15  # 每一步的打字速度 (单位是毫秒)
    cursorSpeed = 1000  # 光标的闪烁速度 (单位是毫秒)
    cursorChar = "|"  # 光标的字符 (支持 HTML 格式)
    duration = -1  # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)

  [params.seo]
    image = "/images/logo.jpg"  # 图片 URL
    thumbnailUrl = "/images/logo.jpg"  # 缩略图 URL

  [params.analytics]
    enable = true
    [params.analytics.google]
      id = "G-TC5F2FT2NP"
      anonymizeIP = false

  [params.cdn]
    # CDN 数据文件名称, 默认不启用
    # 位于 "themes/LoveIt/assets/data/cdn/" 目录
    # 可以在你的项目下相同路径存放你自己的数据文件:
    # "assets/data/cdn/"
    data = "jsdelivr.yml"

[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[author]
  name = "zu1k"
  email = "i@lgf.im"
  link = "https://lgf.im"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
