name: hugo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.2'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install hugo-algolia -g
      - run: echo -e "---\nalgolia:\n  index:\ \"${{ secrets.ALGOLIA_INDEX }}\"\n  appID:\ \"${{ secrets.ALGOLIA_APPID }}\"\n  key:\ \"${{ secrets.ALGOLIA_KEY }}\"\n---" > config.yaml
      - run: hugo-algolia -s
